atk4/ui

- docs/app.rst
- src/App.php
- src/View.php
* implements requireJS and requireCSS methods for App
* adds documentation of new metods
* App now have new property $defaultTemplate = 'html.html' for better configurability
> Implement requireJS and requireCSS

- src/Callback.php
The following code outputs the file but then still proceeds to execute $app->run(). If 'exit' is found inside a call-back we should respect that and don't try to output anything extra.
``` php
$vp = $this->add('Callback');
$vp->set(function() {
highlight_file($_SERVER['SCRIPT_FILENAME']);
exit;
});
$this->link($vp->getURL());
```
> Respect 'exit()' in callback

- js/src/plugins/reloadView.js
- src/jsReload.php
Currently jsReload() contains 2 actions - replace content with spinner, then load new content and replace. This PR combines them into a single method call. This way if we pass some expression based on the content that is about to be reloaded, we won't loose it due to spinner.
``` php
$grid = $page->add('Grid');
$grid->menu->addItem('Complete Selected', new \atk4\ui\jsReload($grid->table, [
'delete'=>$grid->addSelection()->jsChecked()
]));
var_dump($_GET);
```
jsChecked is cleared by spinner and passed as empty string into reloadView.
> Make reload atomic

- docs/grid.rst
- docs/index.rst
- docs/table.rst
- src/Grid.php
- src/Table.php
- src/TableColumn/Actions.php
- src/TableColumn/Checkbox.php
- src/TableColumn/Delete.php
- src/TableColumn/Generic.php
Table will now have controls for displaying sorting (non-interractive) and Grid takes it to the next level by enabling dynamic sorting.
Too bad mouse is invisible...
> Implement Grid Sorting

- demos/database.php
- demos/form3.php
- src/Form.php
- src/FormField/Calendar.php
- src/FormField/Dropdown.php
- src/FormField/Input.php
- src/FormField/Money.php
- src/Persistence/UI.php
- src/TableColumn/Template.php
- template/semantic-ui/html.html
- template/semantic-ui/html.pug
Implemented various improvements for the form:
Now shows currency in a box, not as a text.
Knows visual glitches:
Functionally all works well.
> Form Improvements

- demos/database.php
- demos/form2.php
- docs/form.rst
- src/Form.php
- template/semantic-ui/form.html
- template/semantic-ui/form.pug
New validation now is in line with the Agile Data 1.2 release. Define validations at the model level for multiple fields!
Several other validation ways are depreciated and some major changes which is why we'll pack this into UI 1.2.
- form->setModel() will automatically save() data when submitted, because ... why not?
- form->onSubmit() can execute error as before.
- form->validate hook is no longer there, so we must review code to make sure it's not used in some field.
See if we can address the following issues with this PR:
> Reimplemented Form Validation

- js/src/plugin.js
- src/View.php
When user press cancel on confirm dialog after clicking a table delete
button, the ajaxec plugin is returning an initialized but empty data
object. Therefore, simply testing for an initialized object will
prevent calling ajaxec . We now also check that condition in order to
be able to call ajaxec plugin on an empty object as well.
> Issue #183/Fixed

- demos/button2.php
- demos/init.php
- src/jsCallback.php
Models now throw "ValidationError" when something is wrong with the data. That's not an applicaiton error, if it's left un-cached then the error should be properly presented to the user.
The form already does that by highlighting appropriate field with the error message, but the standard callback handlers based around jsCallback would show an ugly message.
This PR will display validation errors nicely, if developer didn't bother to take care of them.
Demo now have a [failure] button:
Click it to get this prompt:
The responsible code is:
``` php
$b = $layout->add(new Button('failure'));
$b->on('click', function ($b) {
throw new \atk4\data\ValidationException(['Everything is bad']);
});
```
> Implement nice validation error display

- docs/app.rst
- docs/callbacks.rst
- docs/core.rst
- docs/data.rst
- docs/overview.rst
- docs/render.rst
- docs/seed.rst
- src/VirtualPage.php
> Added a lot of documentation on Callbacks, VirtualPages and other topics

- src/View.php
- src/VirtualPage.php
- tests/CallbackTest.php
> Allow virtualpage->set() to accept [$obj, $method]

- src/App.php
- no need to check for $cdn == false here. isset() will do the same.
- add some comments
> No need to check for $cdn existance

- demos/init.php
- demos/modal.php
- demos/modal2.php
- demos/notify.php
- demos/notify2.php
- docs/js.rst
- src/View.php
- src/VirtualPage.php
- src/jsNotify.php
Cleaned up examples and new documentation.
Also contain some fixes to core classes, so review carefully ;)
> Added Documentation fro jsNotify, Modal and jsModal

- features/loader.feature
testing new coverage by adding test for a loader.
> add coverage for loader

- demos/table2.php
- docs/virtualpage.rst
- src/Table.php
- template/semantic-ui/table.html
- template/semantic-ui/table.pug
Tables are good for outputting data from a model, but sometimes you need to add that extra row, some sub-header or subtotal. 
This adds example on how you can do that and adds two new hooks into table: `beforeRow` and `afterRow`
``` php
$table->template->appendHTML('SubHead', '<tr class="center aligned"><th colspan=2>This is sub-header, goes inside "thead" tag</th></tr>');
```
> Improvements for Tables, CRUDS and few other areas.

- src/Form.php
- src/Lister.php
- src/Table.php
Implementation of #292 needs to specify "name" for radio buttons from inside Radio class. Unfortunately currently Radio does not have access to Lister's template.
This PR requires #293 which makes Lister's template available inside init() so we can clone regions right away. This enables the following code:
``` php
$myview->add('Lister', 'MyRows');
$myview->t_row['_name'] = 'abc';
```
- Documentation: n/a
- Demo: n/a
> Move cloneRegion into lister's init

- demos/checkbox.php
- demos/field2.php
- demos/form5.php
- demos/form6.php
- features/loader.feature
- src/FormField/CheckBox.php
- src/FormField/Generic.php
- src/FormField/Input.php
- src/FormField/Radio.php
- src/FormLayout/Generic.php
- src/View.php
- template/semantic-ui/formfield/checkbox.html
- template/semantic-ui/formfield/checkbox.pug
- template/semantic-ui/formfield/radio.html
- template/semantic-ui/formfield/radio.pug
Implementation of radio selection field. Depends on #294. Simple use:
``` php
$form->addField('gender', ['Radio', 'values'=>['F'=>'Female', 'M'=>'Male']]);
```
Works with `enum` and `values`.
- Documentation: [docs/file.rst](docs/file.rst) TODO
- Demo: [demos/file.php](demos/file.php) TODO
> Fix implementation of Radio field

- template/semantic-ui/formfield/input.html
This empty first line caused a space between the <label> and the <div><input><div> which is not neccessary. (In my case caused a problem aligning label and input in one row trying to use 100% width for both of it).
> Removed empty first line

- src/Form.php
This PR fix modal behaviour when an exception is thrown during Form::save()
Somehow, semantic-ui create the modal generated by the exception with css position attribute set to ‘static’, therefore static positioned element are alway stacked under other positioned element, regardless of the z-index attribute.
The fix will close others open modal in order to only show the modal containing the exception thrown by Form::save()
> fix/#318 Form error

- src/FormField/AutoComplete.php
defined in init(), the Autocomplete field requires getting data 'name' and 'id'.
If model->title_field was not 'name' or model->id_field was not 'id', the AutoComplete broke.
I fixed getData() to always return the data as ['id' =>..., 'name' =>...]
A fix in init() was not possible as init() might not know the model.
fixes #327
> fix #327: title_field and id_field

- demos/upload.php
- js/README.md
- js/package.json
- js/src/plugins/fileUpload.js
- src/FormField/Upload.php
- src/FormField/UploadImg.php
$field->set(‘name’, ‘token’) 
Enable setting field name and token to specify pre existing file name and/or token.
```
/**
* Allow to set file id and file name
*  - fileId will be the file id sent with onDelete callback.
*  - fileName is the field value display to user.
*
* @param string      $fileId   // Field id for onDelete Callback.
* @param string|null $fileName // Field name display to user.
* @param mixed       $junk
*
* @return $this|void
*/
public function set($fileId, $fileName = null, $junk = null)
{
$this->setFileId($fileId);
if (!$fileName) {
$fileName = $fileId;
}
return $this->setInput($fileName, $junk);
}
```
```
$img->setThumbnailSrc('./images/logo.png');
```
> Fix/#356 Upload Field Set

- features/bootstrap/FeatureContext.php
- features/form.feature
- js/README.md
- js/src/services/ModalService.js
- src/Form.php
Will autofocus on first field in modal using form.
On dynamic modal, like when use in CRUD, the onShow and onVisible callback are fire prior modal content is loaded.
Therefore semantic-ui modal autofocus has no effects. 
To fix this, we need to manually trigger our autofocus handler function (doAutoFocus) after content is loaded in modal.
The doAutoFocus function is call when modal autofocus is set to true. True is also the default value for modal settings.
To allow for save button to be focusable, the html tag for button is change from div to button. 
js package need to be rebuild.
> Fix/#364 #270

- docs/js.rst
Methods named App::includeJS and App::includeCSS is not found. They seems to be named requireJS and requireCSS.
Implementation of `<new feature>` (see ticket #..). Simple use:
``` php
$app->add(['new component']);
..
```
Typical use case of new feature explained here.
Drag a SCREENSHOT here:
- Documentation: [docs/file.rst](docs/file.rst)
- Demo: [demos/file.php](demos/file.php)
p.s. set label "in review" and assign reviewers if PR is complete. Otherwise set "work in progress" label.
> includeJS -> requireJS / includeCSS -> requireCSS

- demos/reloading.php
- js/README.md
- js/package.json
- js/src/plugins/reloadView.js
- js/src/services/ApiService.js
- src/jsReload.php
Will allow a js function to be run after api onSuccess.
ex: 
```
$val = $app->add(['FormField/Line', '']);
$val->addAction('Set Custom Value')->js('click', new \atk4\ui\jsReload($v, ['val' => $val->jsInput()->val()], $val->jsInput()->focus()));
```
- jsReload.php
- reloadView.js
- apiService.js file.
Note: atkjs-ui need to be rebuild.
> fix/#387-Allow a js function to run after reload is complete.

- src/FormField/AutoComplete.php
Changed
``` $f->model['name'] ```
to
``` $f->model[$this->model->title_field] ```
> Autocomplete to use $title_field instead of 'name'

- src/FormLayout/Generic.php
- tests/FormTest.php
See: https://github.com/atk4/ui/pull/397
---
Added getField-method to Generic Form Layout
See also:
https://forum.agiletoolkit.org/t/split-existing-form-into-tab/447/4
> Cleanup of Pr/397: Added getField-method to Generic FormLayout

- .codeclimate.yml
- demos/init.php
- demos/table2.php
- docs/table.rst
- src/Grid.php
- src/TableColumn/Multiformat.php
- src/Template.php
- tests/DemoTest.php
Implementation of Multiformat column for the table. It allows to use different formatters depending on cell value. Simple use:
``` php
$table->addColumn('amount', ['Multiformat', 'callback'=>function($a, $b) {
if($a['is_invoiced'] > 0) {
return ['Link', 'invoice', ['invoice_id'=>'id']];
} elseif (abs($a['is_refunded']) < 50) {
return ['Template', 'Amount was <b>refunded</b>'];
}
return ['Money'];
}]);
```
Screenshot does not really correspond to example above, but demonstrates 3 different decorators for a same column, including Link+Money, Money and Template.
- Documentation: docs/table.rst
- Demo: demos/table2.php
> Implement "Multiformat" column decorator for table

- demos/autocomplete.php
- src/FormField/AutoComplete.php
Currently using "plus" inside crud pop-up does not work due to 2 reasons:
- virtual page is added into app, therefore loosing some stickyGet set on the modal
- semanticUI pop-up looks messed up appears not on top of existing popup but below it.
> Adding virtualpage into Form makes sure we inherit stickyGet

- src/FormField/AutoComplete.php
Hi there,
I switched the parameter order of array_merge to make overwriting the url setting possible.
Now, something like this works:
```
$ac->setApiConfig([
'url'              => 'my_custom_url',
'allowReselection' => true,
'selectOnKeydown'  => false,
]);
```
Before, the custom URL setting was overwritten by the standard callback URL.
> Allow to override url setting

- src/FormField/AutoComplete.php
Adds a property `limit` which can be used to set a custom limit of records loaded.
This can be very handy in the following case:
Imagine in total its 50 records for this model, 20 of them are used often, the others hardly. Setting the limit to 20 and the sorting to frequency makes the 20 most used records available without typing anything in the text field.
> Allow to set a custom Limit to loaded records

- src/Grid.php
This fix will make sure the draghandler column is set to first column when using drag handler in CRUD with action button.
Otherwise, draghandler column is set after edit / delete button.
> Fix/Crud Draghandler Position

- demos/init.php
- demos/tablecolumnmenu.php
- demos/tablemenu.php
- demos/wizard.php
- docs/components.rst
- docs/grid.rst
- docs/popup.rst
- docs/table.rst
- docs/tablecolumn.rst
- docs/view.rst
- public/agileui.less
- src/App.php
- src/CallbackLater.php
- src/Console.php
- src/FormField/AutoComplete.php
- src/FormField/DropDown.php
- src/Grid.php
- src/Loader.php
- src/Popup.php
- src/SSE.php
- src/Table.php
- src/TableColumn/Generic.php
- src/TableColumn/jsHeader.php
- src/VirtualPage.php
- tests/DemoTest.php
Implements ability to interact with "Columns" of a grid by clicking on icon in the header. This is NOT same as sorting.
Column can be used to implement "column-specific filter" or "hide column" option or any other column-specific interraction through a pop-up.
Usage:
``` php
$column = $table->addColumn('test');
$column->addPopup('test')->add('LoremIpsum');
```
You can also add menus to the column using a callback:
``` php
$column->addDropdown('name', ['one', 'two', 'three'], function($menuItem) {
return 'Selected '.$menuItem;
});
```
The callback is called when user select an item in the menu.
Support grid column too:
```
//Adding a dropdown menu to the column 'name'.
$g->addHeaderDropdown('name', ['Rename', 'Delete'], function($item){
return $item;
});
//Adding a popup view to the column …
```
> Feature/Table Column Menu

- src/View.php
If an array containing only JS actions was used as second parameter of View->on, it failed and threw the error message:
atk4\ui\Exception: You cannot add anything into the view after it was rendered
Now JS actions are merged into $actions array and it works as intended.
Simple test code:
$v_test= $app->add(['Button']);
$v_test->on('click', [$v_test->js()->html('sdfsf'), $v_test->js()->html('ddddd')]);
> Make View->on(event, [jsAction1, jsAction2]) work

- demos/modal2.php
- js/README.md
- js/package.json
- js/src/plugins/createModal.js
- js/src/services/ModalService.js
- template/semantic-ui/modal.html
- template/semantic-ui/modal.pug
Fix multiple modal positioning when using multiple modal;
- Modals under top modal opacity are set to 0, they look hidden but they are still available.
- this is need for modalServices to work properly. 
- We can set the opacity value to an higher number if the intent is still be able to see under modals.
- Proper positioning is done by setting position value to absolute. 
-  Fix the esc key behaviour. Simply adding our own esc event in modal service.
Update modal2.php demos files in order to show modal at three level deep.
atkjs-ui need to be rebuild.
> fix/#487-Modal Behaviour

- src/Grid.php
Add css ‘segment’ class to grid element in order for loader to be display while loading.
resolve #493
> Grid will display loader while fetching data

- demos/tabs.php
- src/CallbackLater.php
Various UI element use CallbackLater. It will divert it's execution until later time, but what if it is already a "later time" ? Currently CallbackLater would divert until "more later time" beforeRender / beforeOutput, but that's not a correct approach, because it would fail third time. 
This PR will execute CallbackLater instantly if it's already late.
resolve #500 
IMPORTANT: this fix was reverted in the past due to: https://github.com/atk4/ui/issues/313. I have tried paginator examples and they seem to work fine.
> Fix problem with multiple callbacks being not executed

- src/App.php
This will catch up callback request when exception occur and properly format server response in order to properly handle exception.
fixes #522
> fix/#522 Ajax error display

- demos/modal.php
- js/README.md
- js/package.json
- js/src/plugins/createModal.js
- public/agileui.less
- src/Modal.php
- src/jsModal.php
- template/semantic-ui/modal.html
- template/semantic-ui/modal.pug
Address issue #538 
- Option to customize header css class for Modal and jsModal;
- Option to customize Loading label in jsModal;
- using jsModal::setOption($options, $value) 
```
$jsModal->setOption('headerCss', 'ui blue header')  //will make header color blue.
```
- using Modal::headerCss property for regular modal.
- at creation time passing an empty, null or false value in title parameter;
- by calling jsModal::removeHeader() method;
- using jsModal::setOption($options, $value) 
```
$jsModal->setOption('label', '')  //set loading label to an empty string
```
> Feature/jsModal options and Modal option

- src/Template.php
In some cases template tags can also contain some other symbols like colon.
There are persistences which allow field names like "cmis:objectType". Grid picks up this field name and creates template tag {$cmis:objecttype}, but Template class don't recognize this as tag because of colon. This commit fixes that.
> Template tags can also contain more symbols, for example, colon

- src/View.php
Currently default app created by view (if you don't have app) may complain about unhandled callbacks.
``` php
$app = new \atk4\ui\App();
$v = $app->add('View');
$logout = new \atk4\ui\Button('Logout');
$logout->init();
$logout->on('click', function() use($app) {
$app->auth->logout();
return new \atk4\ui\jsExpression('document.location.reload()');
});
$v->template->setHTML('Content', $logout->render());
```
> Do not warn about runaway callbacks from "default app"

- src/Console.php
Minor enhancement adding output to console even if you use set().
Currently runMethod() will substitute app->logger to the console itself and will capture all the info() and warning() raised by objects. If you are using set() no such thing is done.
This PR makes set() work similar to runMethod():
> console->set() captures executon info/output.

- demos/database.php
- demos/field2.php
- demos/init.php
- docs/field.rst
- src/FormField/Calendar.php
- src/FormField/Generic.php
* implements `FormField->onChange` method
* works around Calendar field issue (#521)
* it's more intuitive and makes developers life easier :)
* includes demo
* includes documentation
It doesn't use `jsInput()` because it's more limited than `on()` method.
It's implemented in Generic field class because not all fields are Input class fields. For example, checkbox.
Not tested for Checkbox and Radio box fields  tough.
> Implements FormField->onChange method

- public/agileui.less
This css fix will allow table inside grid to overflow horizontally.
Css change is due because  table css class in container for table in grid was remove in PR for column resizer.
> fix/ grid table overflow

- src/View.php
If View is already rendered, but throws exception in json_encode, then you can't add more elements in View so need to set it as not rendered here.
> Set view as not rendered if there is exception

- src/View.php
This enables usage of View::on to pass a PHP callback function as well as several JS actions, e.g.:
```
$this->on(
'click',
'.somecssclass',
[
function($e) {
//PHP Callback
},
(new \atk4\ui\jQuery('#eooSaveButton'))->addClass('loading'),
//someotherJSaction
]
);
```
> View::on now takes callback and JS actions

- src/Modal.php
- template/semantic-ui/modal.html
- template/semantic-ui/modal.pug
Fixes #583 
Added property showActions which is set to true by addButtonAction.
Only if showActions is true the ```<div class="action">``` is shown.
Edit: I am too stupid to work with Github, the template file is missing in this pull request, and I cant get in in here.
```
<{_element}div{/} id="{$_id}" class="{_ui}ui {/} {$class} {_class}{/}" style="{$style}" {$attributes}><i class="{$close}"></i>
<div class="{$headerCss}">{$title}</div>
<div class="img content atk-dialog-content">{$Content}</div>
{ActionContainer}
<div class="actions">
<div>{$actions}</div>
</div>
{/ActionContainer}
</{_element}div{/}>
```
> Only show action <div> if there are actions

- src/App.php
Problem: ATK UI currently disables method signature checking, because PHP 7.0/7.1 does not implement parameter widening correctly.
This has been fixed in 7.2 and by hiding errors we prompt our users to write bad code. 
Read up:
https://wiki.php.net/rfc/parameter-no-type-variance
https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)#Contravariant_method_argument_type
Your code:
``` php
class MyView extends \atk4\ui\View {
public function setModel($m) {
parent::setModel($m);
}
}
```
This code will work OK on 7.2 (because you use type widening), but will fail on 7.0 and 7.1. Which is why we leave warning suppression for those versions. 
Your code:
``` php
class MyView extends \atk4\ui\View {
public function setModel(MyUser $m) {
parent::setModel($m);
}
}
```
This is …
> Allow PHP 7.2+ to check method signatures

- src/Form.php
alike apiConfig and setApiConfig() for adding parameters to FUI .api() function, formConfig and setFormConfig() can be used to add parameters to FUI .form() function, e.g.
```
$orm->setFormConfig(['keyboardShortcuts' => false]);
```
> add formConfig to pass parameters to FUI .form()

- demos/form3.php
never_persist fields are still set in Model->dirty array.
Because of that this demo was confusing because it shows that field value was changed, but user didn't and couldn't change it.
> don't show never_persist fields as changed - that's confusing

- src/FormField/AutoComplete.php
- src/FormField/Lookup.php
Prior to this fix, it was still possible to change readonly state for Lookup or Autocomplete
> fix/Readonly state for Lookup and Autocomplete

- demos/lister.php
- src/Lister.php
- src/Table.php
- src/Template.php
- template/semantic-ui/lister.html
- template/semantic-ui/lister.pug
- template/semantic-ui/table.html
- template/semantic-ui/table.pug
Implements {empty} tag in Lister.
fix #606
> Implements {empty} tag in Lister

- demos/scroll-container.php
- demos/scroll-grid-container.php
- js/src/plugins/scroll.js
- src/Grid.php
See `demos/scroll-grid-container.php`
@ibelar Is it possible to fix load spinner? It should show up in the middle of container like it is doing when you sort grid by some column. Otherwise it's messing up page structure and flickering.
> Make demo for dynamic scroll in container better

- src/FormField/DropDown.php
The stacked ternary operator led to a wrong processing of integer 0 values, this fixes it and the value of the dropdown's hidden input is set correctly to 0 instead of an empty string.
Fixes #618
> Fixes #618: Process fields with integer value 0 correctly

- src/FormField/AutoComplete.php
- src/FormField/DropDown.php
- src/FormField/Lookup.php
To prevent rounding numbers (typically IDs) in JS
The rounding issue has been identified as least in the Semnatic UI Dropdown `set value` and `set  text` APIs.
> Critical bug fix: always convert Dropdown/Autocomplete/Lookup values to string

- demos/scroll-grid-container.php
- src/Grid.php
Don't apply sorting in case sortable=false.
jsPaginator also exclusively calls applySort(), so applySort() should take care of that itself.
> Don't apply sorting in case sortable=false.

- src/View.php
Now will support 'confirm' option also in this case not only when you use callback.
```
$btn->on(
'click',
[
new jsReload($installer, ['start' => 1], null, ['stateContext' => '#'.$btn->name]),
$btn->js()->addClass('disabled'),
],
['confirm' => 'Are you sure you want to install this add-on?']
);
```
> Add "confirm" option support for js->on() case

- src/View.php
Fixes #649 
Will use cb confirm using ajaxexc if available otherwise will pop alert using jsExpression.
> fix/#649 Double Confirm

- src/Template.php
today while i was playing with error catching and i see that there are a bunch of deprecated each functions and i remove it. I see that are covered by PHPUnit and i run tests with success, need to test more even if the use of each was not so extended.
i don't use foreach, because there are some performance issues with memory/pointers, this function is so heavy used and any minimal change in performance on a big layout will result in a huge latency on TTFB.
> Removed deprecated each functions from template parsing

- src/Lister.php
Removed all template cloning and $t_row_clone or $t_row_master etc.
Now it should work as years ago - simple.
Only drawback each next loop iteration will contain values from previous iteration in template tags so even if you want to leave some template tag empty, you have to explicitly set it empty otherwise it will _inherit_ value from previous loop.
> revert lister template changes

- src/TableColumn/Actions.php
See description in #668. fix #668.
> Add container for action buttons

- src/FormField/Radio.php
Update to last Lister commit revert.
- Was still using t_row_master which broke Radio field
> fix/Radio Input Field

- src/FormField/AutoComplete.php
- src/FormField/Lookup.php
- template/semantic-ui/formfield/autocomplete.html
- template/semantic-ui/formfield/autocomplete.pug
- template/semantic-ui/formfield/lookup.html
- template/semantic-ui/formfield/lookup.pug
Various fix for Lookup and Autocomplete field
Fixes #656, #663, #664
- Keep previous select value;
- Proper width apply when used in group;
- Remove empty filter label
> fix/Lookup Autocomplete fixes

- src/FormField/Lookup.php
add definition of plus button, in place of set "plus" => true and add the default label, "plus" => ['icon'=>'plus','class'=>'green']
> Add definition of defaults for Field Lookup

- src/FormField/DropDown.php
- src/FormField/Input.php
- src/FormField/Upload.php
Fix #679
- Apply disable css class only in related input type to prevent opacity rule to be duplicate.
> fix/#679 Disable Input

- README.md
Following the tabs example, typo corrected; otherwise "undefined variable **'tab'** error"
> Tabs example typo correction

- src/Table.php
Implementation of `afterRow` hook
Required in cases where a few more lines are required to be inserted based on the current line after the current row
> afterRow is good to render sub lines related to any line

- docs/form.rst
- src/Form.php
> implement Form->addFields()

- template/semantic-ui/layout/centered.html
Centered layout didnt have any top and bottom padding/margin. On pages that exceeded browsers inner height, that looked quite crappy.
Maybe theres a nicer way using some predefined FUI class?
> add top and bottom padding to centered layout

- demos/multiline.php
- js/Release.md
- js/package.json
- js/src/components/multiline.component.js
- js/src/components/multiline/multiline-body.component.js
- js/src/components/multiline/multiline-cell.component.js
- js/src/components/multiline/multiline-header.component.js
- js/src/components/multiline/multiline-row.component.js
- js/src/services/vue.service.js
- src/FormField/MultiLine.php
New form input in order to allow add/edit multiple record within a form.
```
$f = $app->add('Form');
$f->setModel($invoice, false);
$sub_layout = $f->layout->addSubLayout('Generic');
$sub_layout->setModel($invoice, ['name', 'client_id', 'address']);
$sub_layout = $f->layout->addSubLayout('Generic');
//Add multi line input to the layout.
$ml = $sub_layout->addField('ml', ['MultiLine']);
$ml->setModel($invoice, ['item','cat','qty','price', 'sub', 'tx', 'grd'], 'Items', 'invoice_id');
// add onchange handler and update grand total.
$ml->onChange(function($rows) use ($f) {
$total = 0;
foreach ($rows as $row => $cols) {
foreach ($cols as $col) {
$fieldName = key($col);
if ($fieldName === 'grd') {
$total = $total + substr($col[$fieldName], 4);
}
}
}
return $f->js(true, null, …
```
> features/MultiLine Form Field

- src/Card.php
Allow to used only certain columns in Model to be displayed in Card.
```
$card->setModel($invoice_model, ['client','balance', 'paid_total','g_total']);
```
> feature/Card Column

- src/App.php
if you extend App class and want to use routing in place of direct call to files, you have to complete override the method url of App, to change only 2 occurence of ".php", even if the first occurence at line 542 is only for completeness, the other one on line 587 must be changed to avoid reparsing the result of a parent::url(args) if you plan to only partially override that is nonsense.
i put the variable protected because is something that never change and must work in extended class.
> Allow easy routing implementation

- js/Release.md
- js/babel.config.js
- js/package.json
- js/src/plugins/create-modal.plugin.js
- js/src/plugins/file-upload.plugin.js
- src/FormField/Upload.php
- src/jsModal.php
- Babel configuration.
- fix core.js warning during build.
- file-upload.plugin
- remove support for opening file dialog when input get focus. Because File dialog
will blur and re focus input field again. This was causing file dialog to open
multiple times. Now only open when input or button is clicked.
- create-modal.plugin
Now allow to pass css class name to create modal.
Useful when need to create modal with full width for example.
``` php
$btn = $app->add(['Button', 'Add']);
$btn->on('click', (new jsModal('Add new', $vp))->setOption('modalCss', 'fullscreen'));
```
> fix/File upload - jsModal Css

- src/CRUD.php
- src/Grid.php
> Fix #719 and #720

- src/TableColumn/Generic.php
In Model we can define the default caption for the field, usually in Table we use abbreviation or acronim of that long caption, to centralize TableColumn the definition of the ui rappresentation of the field in all table.
> Add TableColumn Caption definition in model

- src/App.php
Currently `atk4\ui\App` normalize class will prepend `\atk4\ui\` when using short name of the class, like this:
``` php
$app->add('CRUD');
```
However, this requires us to always use full name for the class:
``` php
$app->add('\my\test\MyClass')
```
This is incompatible with:
``` php
use \my\test\MyClass;
$app->add(MyClass::class);
```
because it uses `my\test\MyClass` without opening backslash.
This PR fixes problem by checking for the presence of the class inside \atk4\ui\ before attempting to use the prefix.
> Only prepend namespace for known classes

- src/Header.php
Should better check for numeric value not int.
For example, string '3' is not int, but is numeric and sometimes we get numbers as strings.
> should check numeric value not int

- src/Header.php
- src/Table.php
Fix table column decorator in case of negative status
> fix negative status

- demos/dropdown-plus.php
- demos/init.php
- docs/field.rst
- src/FormField/DropDown.php
- template/semantic-ui/formfield/dropdown.html
Adds property renderRowFunction, which can be used to pass custom html options to renderView for each option.
If not defined, only needed title_field and id_field are used. (and system fields, they are also loaded when using only_fields()).
> Fix #629, also add new Callback for custom HTML

- src/Form.php
- src/jsCallback.php
Fixes:
- Allow to pass a view  and return a view to form success callback.
-  jsCallback return response from duplicating Modals dialog.
```
$f = $app->add('Form');
$f->setModel($country);
$f->onSubmit(function($f){
$modal = new \atk4\ui\View();
$modal->add(new \atk4\ui\Message(['Country is saved.', 'text' => 'What will you like to do?']));
$modal->add($newBtn = new \atk4\ui\Button('Add New Country'));
$modal->add($editBtn = new \atk4\ui\Button('Edit Country'));
$newBtn->on('click', [$modal->js()->parents('.modal')->modal('hide'), $f->jsReload()]);
$editBtn->on('click', [$modal->js()->parents('.modal')->modal('hide')]);
return $f->success($modal);
});
```
Will display:
> Fix/Form::success()

- demos/database.php
- demos/form3.php
- demos/somedatadef.php
- demos/table2.php
- src/CardTable.php
- src/Component/InlineEdit.php
- src/FormField/Lookup.php
- src/FormField/MultiLine.php
- src/FormLayout/_Abstract.php
- src/Grid.php
- src/Persistence/POST.php
- src/Persistence/UI.php
- src/Table.php
- src/TableColumn/FilterModel/TypeDate.php
- src/TableColumn/FilterModel/TypeDatetime.php
- src/TableColumn/FilterModel/TypeNumber.php
- src/TableColumn/FilterModel/TypeTime.php
- src/TableColumn/Link.php
atk4\data (`develop`, v2 branch) is now expects you to use `$model->getFields()`. I have refactored by removing any uses of $model->elements directly (except when it's used with a View).
> refactor to use getFields()

- .travis.yml
- composer.json
- demos/console.php
- demos/database.php
- demos/db.example.php
- demos/popup.php
- demos/sse.php
- demos/wizard.php
- phpunit.xml.dist
- src/App.php
- src/Exception/ExitApplicationException.php
- src/FormField/Lookup.php
- src/FormField/Upload.php
- src/Grid.php
- src/ItemsPerPageSelector.php
- src/SSE.php
- src/TableColumn/FilterModel/Generic.php
- src/TableColumn/Generic.php
- src/TableColumn/jsHeader.php
- src/jsPaginator.php
- src/jsSSE.php
- src/jsSortable.php
- tests/DemoTest.php
Hope this fixes #651, but probably it will solve strange issue of no feedback in other components of ui.
what i have done : 
- I need to remove some notice suppressor in code.
- i use php 7.2 syntax, because composer now require php >= 7.2
- i removed some code that is not need anymore.
- Now any error will be raised as an exception
- Error and Exception will be handled by $app->caughtException($e)
Sample case to compare with previous version :
```php
require 'vendor/autoload.php';
$app = new \atk4\ui\App();
$app->initLayout('Centered');
$modal = $app->add(['Modal']);
$modal->set(function($m) use ($modal) {
throw new \Exception("TEST!");
});
$button = $app->add(['Button', 'Test modal exception']);
$button->on('click', $modal->show());
$modal2 = $app->add(['Modal']); …
```
> Fix #651 - Modal fails on js load if a php exception is thrown

- src/FormField/Calendar.php
- src/Persistence/UI.php
User will be able to overwrite all options mentioned here ( https://github.com/mdehoog/Semantic-UI-Calendar ) in an easier, more intuitive way by extending UI persistence like that:
```
class UI extends \atk4\ui\Persistence\UI
{
public $date_format = 'd.m.Y';
public $time_format = 'H:i';
public $datetime_format = 'd.m.Y H:i:s';
// 'D, d M Y H:i:s O';
/**
* Calendar input first day of week.
*  0 = sunday;.
*
* @var int
*/
public $firstDayOfWeek = 1;
public $currency = '€';
public $yes = 'Ja';
public $no = 'Nein';
public $options = array('today' => true,
'monthFirst' => false,
'touchReadonly' => true,
'startMode' => year,
'ampm' => false,
'formatInput' => true,
'multiMonth' => 1,
'text' => array(
'days' => ['S', 'M', 'D', 'M', 'D', 'F', 'S'],
'months' => ['Januar', 'Februar', 'März', …
```
>  Let user overwrite all calendar options

- src/App.php
Currently ATK UI uses static() in caughtException() in order to display the exception within the app's environment. However, this can lead to complications like those:
And in modals:
This PR addresses the issue by creating a new App() to display the exception and also adds the line and exception title in the page's title which can be practical when juggling with exceptions.
> Fix #786 - Exception display in app and modals

- tests/ForFieldUITest.php
Implementation of `New test case for ui=>editable test`  (by @gowrav-vishwakarma )
``` php
$this->addField('no_persist_but_show_in_ui',['never_persist'=>true,'ui'=>['editable'=>true]]);
// this should not be readonly in ui
..
```
closes #698
> Gowrav vishwakarma ui editable bug

- docs/icon.rst
- src/View.php
- src/jsSearch.php
This PR adds the ability to specify a `target` attribute within the `link()` function, which allows the opening of the page in a new tab.
*Note: This shouldn't break any existing code as the argument is optional.*
For example:
```
// Open in new tab
$app->add(['Label', 'Open page in a new tab'])->link(['my-page'], '_blank');
// Open in same tab as before
$app->add(['Label', 'Open page in a new tab'])->link(['my-page']);
```
> Add target parameter to link() function

- src/App.php
apache gives error on extra spaces for header of Content-Type
> remove extra spaces from Response Content-Type

- src/TableColumn/FilterModel/TypeString.php
add "Is Not" option for TableColumn::FilterModel::TypeString
https://puu.sh/E9Rqy/5e2cdd5908.png
> add "Is Not" for TableColumn::FilterModel::TypeString

- src/App.php
Need to send proper class identifier when App is extended and initLayout is override like below. Otherwise, layout class is not found and exception is never shown. 
```
public function initLayout($seed, $options = [])
{
$ret = parent::initLayout($this->factory($seed, null, '\saasty\frontend\Layout'));
// code here
return $ret;
}
```
With current implementation, it will try to create layout using 'sassy\frontend\Layout\Centered' which does not exist.  This fix make sure we are passing the right class name to initLayout.
> fix/CaughException Layout

- demos/modal.php
- docs/js.rst
- src/Modal.php
- template/semantic-ui/modal.html
**Attention:** Credit for this PR goes to @PhilippGrashoff who is the real contributor of this code. For more info see #793.
> This adds the ability to customize the CSS classes which are used for the `<div class="img content atk-dialog-content>"`. E.g. add 'scrolling' for scrolling content.
>
> Also fixes Method addScrolling, which added the 'scrolling' class to the main div instead of the content div.
>
> If you think defining an extra method for it is overkill, we could go the same way as $headerCss is.
> Add ability to customize CSS of 'content' div

- src/App.php
add App->catch_error_types = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_USER_DEPRECATED;
Can be used to define set_error_handler error types without overriding the construct of the App.
Previously was hardcoded and to change it you must extend App and override __construct.
> Add App->catch_error_types to define set_error_handler in App

- demos/field.php
- src/FormField/AutoComplete.php
- src/FormField/DropDown.php
- src/FormField/Input.php
- src/FormField/Lookup.php
- src/FormField/TextArea.php
Until now, only attributes could be set to the surrounding <div class="field"> using $formfield->setAttr(). This PR makes it possible to add attributes directly to the <input> tag: 
New property added: $this->inputAttr in which additional attributes are stored
New function added: setInputAttr() which is a clone of View->setAttr() which fills the $this->inputAttr array
Can also be used to overwrite existing attributes as $this->inputAttr is passed as second param to array_merge (at $this->app->getTag())
> Formfields: Add ability to set attributes to <input> Tag

- template/semantic-ui/formfield/autocomplete.html
- template/semantic-ui/formfield/autocomplete.pug
- template/semantic-ui/formfield/lookup.html
- template/semantic-ui/formfield/lookup.pug
In Autocomplete and Lookup controls, a large area of the control is unclickable, showing a hand cursor. This makes those controls effectively unusable.
The issue is reproducible in the current demo (for example https://ui.agiletoolkit.org/demos/autocomplete.php - hovering over Country1/2/3 towards the right will produce the hand cursor and unclickable control).
This PR fixes the issue for both controls.
> Fix unclickable Autocomplete/Lookup fields

- js/src/plugins/js-search.plugin.js
Implements #711
* Pressing Escape on Grid QuickSearch clears its text.
* Pressing Escape when the text is empty bubbles up the event.
Note: to be able to use this, you will need the compiled JS file, or when a new ATK UI release will be made.
> Make Escape key clear Grid Search

- demos/multiline.php
- js/Release.md
- js/package.json
- js/src/components/multiline.component.js
- js/src/components/multiline/multiline-body.component.js
- js/src/components/multiline/multiline-row.component.js
- src/FormField/MultiLine.php
- Add new row of data when tabbing out of last row/column when option is on.
- Ability to run js code when adding or deleting row of record.
fixes #813
> Fix/MultiLine Improvement

- README.md
- locale/.empty
- src/Locale.php
- tests/LocaleTest.php
Add Locale class to find default localization definitions
> Add Locale class

- demos/tree-item-selector.php
- docs/tree-item-selector.rst
- js/Release.md
- js/package.json
- js/src/components/tree-item-selector/tree-item-selector.component.js
- js/src/services/vue.service.js
- src/FormField/TreeItemSelector.php
- Will display a list of items in a hierarchical (tree) like structure and collects id's select by user. 
- Work in multiple selection mode (allowMultiple = true) or single selection mode.
See './demos/tree-item-selector.php' for more detail on how to setup and use this input field.
> feature/TreeItemSelector Form Field

- .gitignore
- demos/jsargumentform.php
- js/Release.md
- js/package.json
- js/src/agile-toolkit-ui.js
- js/src/helpers/url.helper.js
- js/src/plugins/ajaxec.plugin.js
- js/src/plugins/reload-view.plugin.js
- js/src/services/data.service.js
- js/src/services/modal.service.js
- src/ActionExecutor/Preview.php
- src/ActionExecutor/UserAction.php
- src/ActionExecutor/jsArgumentForm.php
- src/ActionExecutor/jsEvent.php
- src/Loader.php
- src/TableColumn/Actions.php
- src/View.php
- src/jsCallback.php
- src/jsReload.php
User Action Executor allows you to bind UI elements with User Actions defined in the model. 
Conveniently executor will ask user for missing arguments, provide user with a preview, if action supports a preview and will also show the result of action execution.
More information is comming.
> Refactor of User Action Executor

- src/FormField/DropDown.php
Remove unneccessary property isValueRequired in FormField/DropDown and rely on field property required instead.
Fixe #513
> fix/DropDown Unnecessary isValueRequired property

- src/FormField/Money.php
- src/Persistence/UI.php
Implementation of `currency_decimal property in UI persistence`. Simple use:
``` php
$app->ui_persistence->currency_decimals = 2; // default
// Typical US large or estimate type amount use:
$app->ui_persistence->currency = '$';
$app->ui_persistence->currency_decimals = 0; // no decimals
// When dealing in fractions of a penny type numbers
$app->ui_persistence->currency_decimals = 4; 
..
```
Displaying money type (currencies) with custom or zero decimal points. It is very common in business to chop off decimals for larger numbers.
Drag a SCREENSHOT here:
> Property currency_decimal added to Persistence UI (Money Type)

- demos/sse.php
This adds an example for triggering an SSE operation after asking confirmation from the user.
> Add SSE operation with user confirmation example

- src/ActionExecutor/UserAction.php
- src/Callback.php
- src/Loader.php
Sometimes, callback argument need to stick application-wide, not just in View.
This is especially true for ActionExecutor using application modal.
This PR allows us to create a URL argument that stick to application.
> Fix/Enable Callback argument to stick at application

- src/App.php
Change string quotes from double quotes to single quotes as the double quotes with current complex content is not parsed by Netbeans correctly. No functional change.
Before:
After:
Also reporting to the Netbeans - https://issues.apache.org/jira/browse/NETBEANS-3782 . Please fix here too for cleaner code and to make autocomplete/refactoring working before it is fixed in Netbeans.
PS: I also checked other files matching `^[^"\n]*("[^"\n]*"[^"\n]*)*"[^"\n]*\$[^"\n]*"` regex but this seems to be the only issue.
> Update string quotes to make the code compatible with Netbeans

- docs/template.rst
- src/Template.php
- tests/TemplateTest.php
Allows to use special _conditional_ tags `{tagname?}` in Template which will automatically remove respective template region in case `tagname` value is set to empty (string, false, null, 0).
For example,
```
$s = 'My {email?}e-mail {$email}{/email?} {phone?}phone {$phone}{/?}. Contact me!';
$t = new \atk4\ui\Template($s);
$t->set('email', null);
$t->set('phone', 123);
$this->assertEquals('My  phone 123. Contact me!', $t->render());
```
> Implement conditional tags in template

- js/Release.md
- js/package.json
- js/src/services/api.service.js
> Fix/Clear Api Data with all server response

- tests/Concerns/HandlesTable.php
- tests/GridTest.php
- tests/TableColumnColorRatingTest.php
- tests/TableColumnLinkTest.php
- separate common code in a trait
- rename method to a more intuitive name
- allow for selecting data-id of table row to extract
- strip newline to ensure string comparison passes
- use new array persistence class
> use trait for table tests

- demos/menu.php
- src/Menu.php
This way we will no more see empty menu containers in our generated HTML including CRUD menu.
fix #908
> Don't render Menu if it's empty

- src/FormField/AutoComplete.php
- src/FormField/DropDown.php
- src/FormField/Lookup.php
> Change Dropdown, Autocomplete and Lookup empty value to Unicode NBSP

- tests/DemoCallExitTest.php
Important when `open_basedir` is active to never access parent directory which may be outside.
> Swap conditions, prevent ".." file lookup

- .github/workflows/unit-tests.yml
Currently, if test for one PHP version fail, see https://github.com/atk4/ui/actions/runs/36201430 , other tests are cancelled. This PR fixes GH Actions to behave like TravisCI.
> Do not fail-fast PHP test matrix

- src/ActionExecutor/UserAction.php
Properly catch Data Validation error in UserAction executor.
> Fix/UserAction Validation error

- tests/BuiltInWebServerAbstract.php
- update test web server root directory to always be `atk4/ui` package root directory instead of using current working directory which prevented from running test files individually
- introduce private methods to cleanup code
> set test web server root to package root directory

- tests/DemoCallExitTest.php
- update regex from any char to matching chars literally
- ignore newlines when comparing the formatting result with actual response
> use regex with full string match on SSE response keys

- public/agileui.less
- src/TableColumn/Generic.php
- tests/BuiltInWebServerAbstract.php
fixes #554
a4d8720 is the actual fix
5b958f7 refactoring of variable names and using shorthand syntax for clarity
Print screen of the solution in action:
> [FIX] table column actions icon

- src/ActionExecutor/UserAction.php
- src/Modal.php
Allow to customize the Modal title for UserAction via Modal:: title property.
- if title property is null, then it will default to Action and Model caption.
> fix/UserAction Title

- demos/database.php
- docs/grid.rst
- public/agileui.less
- src/Grid.php
- src/TableColumn/Generic.php
- src/TableColumn/Password.php
Can be set directly in UI or by using model:
```
// do not allow sorting for this field/column
$model->addField('foo', ['ui' => [
'table'=>['sortable' => false],
]]);
```
> Implement $sortable property for TableColumn.

- js/Release.md
- js/babel.config.js
- js/package.json
- js/webpack.config.js
Update dependencies
- update Babel  which rely on Minimist
├─┬ @babel/core@7.8.7
│ └─┬ json5@2.1.2
│   └── minimist@1.2.5 
- update Babel configuration to use corejs 3
Fix: #994
> fix/Js Package Dependencies

- src/jsFunction.php
Use cases:
```
// some long code typically from a file - end semicolon is almost always already presented
$code = <<<EOT
long code here();
long code here();
long code here();
EOT;
new \atk4\ui\jsExpression($code);
```
```
// statement that is surrounded with block brackets - end semicolon is not needed
new \atk4\ui\jsExpression('if (true) {}');
```
> Do not append semicolon to statement when not needed

- src/TableColumn/Labels.php
Fix TableColumn\Labels for null values
if $v is null => cast to enpty array.
``` 
foreach ((Array) $v as $id) {
$id = trim($id);...	         
```
> Fix TableColumn\Labels for null values

- demos/upload.php
- src/FormField/Upload.php
This fix will prevent throwing an error about onDelete or onUpload callback not been set when running within another callback.
Fix: #1029
> [fix] - Allow onDelete or onUpload callback to run within another callback
