demos/form2.php, demos/reloading.php, js/README.md, js/src/plugins/reloadView.js, src/Form.php, src/FormField/Input.php, src/jsReload.php
Trying to implement similar functionality as in:
https://github.com/atk4/sink/blob/develop/admin/page/js/boysngirls.php#L31
=> Allow to pass argument to jsReload()

docs/menu.rst
Documentation for Menu class , #96
=> Add missing menu documentation, resolve #96

demos/init.php, demos/sticky.php, src/App.php, src/View.php, template/semantic-ui/html.html
Implemented $app->stickyGet()
TODO: add docs
=> implement Sticky Get

src/Form.php, src/FormField/Password.php, src/Table.php, src/TableColumn/Password.php
Implements password field:
* new TableColumn - in Table will show *** instead of actual value
* new FormField - in Form will use input type=password
* fixes #141
=> Implements password field

demos/demo.php, demos/templates/layout1.html, demos/templates/layout1.jade, demos/templates/layout2.html, demos/templates/layout2.jade, docs/app.rst, docs/overview.rst, template/semantic-ui/html.html, template/semantic-ui/html.pug
A better implementation than https://github.com/atk4/ui/pull/148
=> fix dependencies to use proper CDN /https for #147

src/Table.php
Adds more customization options for Table totals
* add `min`, `max`, `count` aggregate methods for Table totals
* add Closure support for Table totals
=> Adds more customization options for Table totals

template/semantic-ui/layout/centered.html, template/semantic-ui/layout/centered.pug
=> Scrolling overflow issue resolved in layout center.

src/App.php
* sticky args should be added even if we use current page in URL
* adds comments and slightly shorten code
=> Fix sticky args in URL

docs/quickstart.rst
Explained how to run this example as an application
Corrected a bug in setting the model in the grid
=> Some clarification on the Quickstart page and a bug fix in the todo example

demos/crud2.php, src/Grid.php, src/Table.php, tests/DemoTest.php
resolve #229 - Grid wasn't displaying "boolean" with status decorator.
=> Fix issues caused by upgrading Agile Core

codecov.yml, demos/loader.php, js/README.md, js/src/services/ApiService.js
Added a new demo. If you click the button, however, the exception is generated and displayed incorrectly by the frontend JS du eto #234
=> Add loader demo which triggers #234 error

src/FormField/Calendar.php
To make life easier to find Calendar docs.
=> Inserted a link to calendar github page in comment

demos/init.php, demos/lister.php, demos/table.php, docs/lister.rst, docs/table.rst, src/Lister.php, src/View.php, template/semantic-ui/lister.html, template/semantic-ui/lister.pug, tests/DemoTest.php, tests/ListerTest.php
Implementation of Lister see #11, #23 and #27. Simple use:
``` php
$app->add(['Lister', 'defaultTemplate'=>'lister.html'])->setSource([
['icon'=>'map marker', 'title'=>'Krolewskie Jadlo', 'descr'=>'An excellent polish restaurant, quick delivery and hearty, filling meals'],
['icon'=>'map marker', 'title'=>'Xian Famous Foods', 'descr'=>'A taste of Shaanxi\'s delicious culinary traditions, with delights like spicy cold noodles and lamb burgers.'],
['icon'=>'check', 'title'=>'Sapporo Haru', 'descr'=>'Greenpoint\'s best choice for quick and delicious sushi'],
]);
```
or
``` php
$view = $app->add(['View', 'template' => new \atk4\ui\Template('
<div class="ui header">Top 20 countries (alphabetically)</div>
{List}<div class="ui icon label"><i class="{iso}ae{/} flag"></i> {name}andorra{/}</div>{/} …
```
=> Added implementation of Lister

src/FormField/Generic.php, src/FormField/Hidden.php, src/FormLayout/Generic.php
Fix hidden input type rendering.
Prevents label from being output when defining an hidden input type.
=> Fix Hidden type field label display

src/App.php, src/CallbackLater.php, src/View.php
Fixes #313 by reverting a change introduced in #297 .
https://github.com/atk4/ui/pull/297/files#diff-d36b8180c676ceb4cd32cea1f15f2de2L20
=> resolve #313

docs/view.rst, src/View.php
Implementation of jsReload()
``` php
$button->on('click', $anyview->jsReload());
```
Simpler implementation, also does not have a problem if `jsReload` class is not reachable during reload.
=> Add View::jsReload()

demos/tabs.php, src/Tabs.php
Just fixes tab callback, currently in includes layout too, but must cut page content only.
=> fix tab callback

README.md, features/js.feature
=> Updating readme for 1.4

features/bootstrap/FeatureContext.php, features/js.feature, src/jsCallback.php, src/jsSSE.php
Validation was not returning proper error msg.
=> fix jsCallback catch on Validation Exception

js/README.md, js/package.json, js/src/agile-toolkit-ui.js, js/webpack.config.js
- Add version function;
- a long due Readme file update.
Now possible to output the atk version number in console using:
```
atk.version()
```
=> Feature/js package 1.0.1

CHANGELOG.md, src/App.php, src/View.php
Some minor cleanups of the code.
=> Small cleanups

demos/button.php
Simply clean up demos/button.php
=> Cleaned up button demo

src/App.php
Just update of 3rd party library versions.
=> Update semantic UI to 2.3.0 and jQuery to 3.3.1

demos/form.php, demos/modal.php, demos/modal2.php, demos/tabs.php, demos/virtual.php, docs/app.rst, docs/autocomplete.rst, docs/tabs.rst, src/App.php, src/Callback.php, src/Form.php, src/FormField/AutoComplete.php, src/FormField/Upload.php, src/Loader.php, src/Modal.php, src/SSE.php, src/Tab.php, src/TableColumn/Delete.php, src/Tabs.php, src/View.php, src/VirtualPage.php, src/jsCallback.php, src/jsModal.php, src/jsReload.php, src/jsSSE.php, src/jsSearch.php
Revision using App:jsUrl() without view property.
resolves #369
=> Feature/jsUrl Rev

demos/autocomplete.php
Removed old "return" to see the complete demo
=> Removed "return" in demo which was blocking some examples.

.codeclimate.yml, src/CRUD.php, src/FormField/AutoComplete.php, src/FormField/DropDown.php, src/Lister.php
Refactor code to use getTitle() and getModelCaption() which were introduced in 
https://github.com/atk4/data/pull/299#pullrequestreview-104895555
Functionality must not be affected.
=> Make use of getTitle() and getModelCaption()

src/App.php
Update semantic-ui to version 2.3.1
=> semantic-ui release update

js/README.md, js/package.json, js/src/plugins/ajaxec.js
Prevent atkAjaxec from firing if the attached html element has previously fired the action and the action is actually loading.
atkjs-ui.js need to be rebuild.
=> Fix/#452 Grid action button

demos/console.php
add warnings in Console tests for Windows
=> add warnings in Console tests for Windows

docs/form.rst, src/Form.php
Using setApiConfig(), additional parameters can be passed to Semantic UI .api function which does the AJAX submission of the Form. Code is cloned from AutoComplete.php
=> Added setApiConfig() function to Form.php

src/Menu.php
otherwise we get
`Notice: Undefined index: icon in C:\wamp64\www\saasty.io\vendor\atk4\ui\src\Menu.php on line 125`
=> bugfix if icon is not set

src/FormLayout/_Abstract.php
Fix issue where cannot find Exception class when an error is thrown.
=> Fix/#480 Unable to find Exception

src/jsNotify.php
=> Fix/#478 Notify options

src/TableColumn/FilterModel/TypeDatetime.php
=> Add FilterMode\TypeDatetime

src/LoremIpsum.php
LoremIpsum class didn't support seed mechanism. Now it's fixed in backward compatible way.
=> Fix LoremIpsum constructor (seed mechanism)

src/Grid.php
Fix problem with $grid->jsReload not showing reload indicator
=> $grid->jsReload not showing reload indicator

README.md, src/App.php
Implements #523 
CDN: https://cdn.jsdelivr.net/npm/fomantic-ui@2.5.0/dist/semantic.css
=> Upgrading to Fomantic-UI

src/Grid.php
=> Sorting should happen later. Fix #544

demos/init.php, demos/toast.php, src/App.php, src/jsToast.php
Usage:
```
$btn = $app->add('Button')->set('Success');
$btn->on('click', new \atk4\ui\jsToast([
'title'   => 'Success',
'message' => 'Well done',
'class'   => 'success',
]));
```
See toast.php in demos.
=> Feature/Toast Module - Fomantic 2.6.4 Release

demos/autocomplete.php, src/CRUD.php, src/Grid.php, src/ItemsPerPageSelector.php, src/Paginator.php
Fixes #573 
Also fix pageSelector sorting.
=> Fix/#573 Memorize url

template/semantic-ui/html.html, template/semantic-ui/html.pug
=> Fix mobile layout

src/View.php
=> comment fix

demos/form2.php, docs/form.rst, src/Form.php, src/FormLayout/Custom.php, src/FormLayout/Generic.php, src/FormLayout/_Abstract.php
Now can use like this:
`$this->add(new Form(['buttonSave'=>false]))`
Maybe even could add ability that if buttonSave is array, then pass it as seed to addButton() method, but not sure about that. How you think?
=> add ability to set buttonSave=false to not create it

demos/form2.php, src/Form.php
Use Lookup field for hasOne, fix #636
=> Use Lookup field for hasOne, fix #636

src/Persistence/UI.php
Any dev can now derive the class or set the properties to have the stuff localized
=> Update UI.php to let dev decide about naming

src/Lister.php
We need clone here, but it's ok because it's not repeated in a loop.
=> fix Lister

js/Release.md, js/package.json, js/src/plugins/notify.js
- Will also work under Fomantic v2.7.2
=> fix/jsNotifier Transition

src/App.php
Update to Fomantic version 2.7.2
=> Feature/Fomantic Update

src/FormLayout/_Abstract.php
Should use read_only property instead of disabled.
Also helps (as workaround) for #679
=> use read_only instead of disabled property

docs/quickstart.rst
Currently receiving: 
**Fatal Error**
atk4\ui\Exception: Unable to set property for the object
```
Exception Parameters
object: atk4\ui\CRUD ()
property: "ops"
value: {"c":false,"d":false}
```
However, removing the `opt` array appears to resolve the issue and the example works accordingly. Additional edits to update corresponding documentation line numbers.
=> Fatal Error attempting to set grid options.

demos/menu.php, src/DropDown.php
Implementation of `Adding on change event to Dropdown View using callback` 
Possibility to add an onChange callback function when user changes dropdown item value.
Simple use:
``` php
$dropdown = $app->add(['DropDown', 'Title', 'js' => ['on' => 'hover']]);
$dropdown>setSource(['Item a', 'Item b', 'Item c']);
$dropdown->onChange(function($item) {
return 'New seleced item: '.$item;
});
```
demos/menu.php
=> feature/Dropdwon callback.

docs/overview.rst
Implemented punctuation changes (Oxford comma), syntax checks, copyright name correction (WordPress capital ‘p’, etc.). Changes for clarity, subject phrasing, run-ons, etc.
=> Grammar, syntax, copyright name, spell check 

demos/header.php, demos/label.php, docs/header.rst, docs/image.rst, docs/label.rst, src/App.php, tools/release.sh
Change CDN from rawgit to jsDeliver
Resolves #685
=> Change CDN from rawgit to jsDeliver

src/Grid.php, src/jsSSE.php
with nginx header('X-Accel-Buffering:no') is needed.
Can be tested in the demo site . https://ui.agiletoolkit.org/demos/sse.php
more info here : http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffers
=> prevent nginx caching

docs/overview.rst, docs/quickstart.rst
Some documentation spelling corrections and improvements.
=> overview.rst corrections

src/FormLayout/_Abstract.php
Fixes #695 by adding addFields() function in _Abstract.php.
=> Add addFields() in _Abstract.php

src/FormField/CheckBox.php
=> #730 checkbox missing use Exception

src/TableColumn/ColorRating.php, tests/DemoTest.php, tests/TableColumnColorRatingTest.php
my PR #726 was added without unit test and documentation.
i started adding some tests for normal behaviour and adding comment where needed.
I put a labels for documentation needed, because i tried to document something and i see that i'm not so good in this.
=> Add Unit test and Fix some issue on TableColumn\ColorRating

demos/form.php, src/FormField/DropDown.php, src/FormField/TextArea.php
=> Revert "fix #755"

demos/grid_action.php, src/ActionExecutor/Basic.php, src/ActionExecutor/Form.php, src/ActionExecutor/Preview.php, src/CRUD.php, src/Grid.php, src/Table.php, src/TableColumn/Actions.php
Create Form action executor for grid user action
- enable to edit record via action;
Grid may also add Preview executor
- Example for delete purpose where user can confirm action.
=> feature/Form Action Executor

js/package-lock.json, js/package.json
Upgrade npm dependencies... @ibelar is that ok?
=> upgrade npm

src/Form.php, tests/FormTest.php
Just a bit of Form() testing making sure it's parsing POST correctly.
=> Implement $_POST test for Form

src/View.php
It just simplifies this method.
=> Simplify setStyle method

src/FormField/MultiLine.php
This is a rewrite/correction/improvement of several inline documentation and comments of Multiline Field. This PR is safe, only comments have been changed.
=> Mutliline: Improve inline docs and comments

src/App.php, src/FormLayout/Custom.php
Small phpdoc fixes, please see #823 for more information.
=> #823: Fix a few phpDoc comments.

src/App.php, src/FormLayout/Custom.php
These fixes are already merged to `develop` (2.0), so this is just about doing similar changes in `legacy/v1`.
Issue #823 contains more information.
=> #823: Fix a few phpDoc comments (for legacy/v1)

demos/actions.php, demos/jsactions.php, features/lookup.feature, src/ActionExecutor/Basic.php, src/CRUD.php, src/Grid.php, src/jsNotify.php, src/jsToast.php, tests/DemoCallExitTest.php
=> Fix few bugs and add comments

demos/index.php, demos/init.php, demos/tutorial_actions.php, demos/view.php
Display code in demo tutorial using Highlight.js
=> Feature/Code Highlight

docs/quickstart.rst
Add documentation to use DIContainerTrait "features" to instantiate App
=> Add Instantiate App using DIContainerTrait

composer.json, docs/quickstart.rst, src/App.php
=> Release/2.0.1 backport.

docs/filestructure.rst, docs/index.rst, docs/quickstart.rst
I adapted and enhanced the things that have been missing for myself when I started using atk. So I first had to dig into namespaces and second I had to experiment with the file structure until I came up with one that is suited for small and big projects and offers a good overview and structure.
Useful for beginners that have first contact with atk and aren't used to PSR-4 namespaces and have just low level skills in dealing with Composer.
=> Added namespaces to quickstart and file structure example

src/Card.php
Use all visible model fields by default in Card.
=> Feature/Card Field default

demos/crud.php, src/CRUD.php
Fix callback for Form. Was broken by PR#880
- Refactor some method name.
- Fix CRUD demos/crud.php
=> Fix/CRUD onForm callback

src/Grid.php
=> [REFACTOR] use same one-liner to shift selector column as on drag handler

src/CRUD.php
Now `add` action in CRUD will respect `enabled` property.
=> Add action should respect enabled/disabled switch

demos/tablecolumnmenu.php, public/agileui.less, src/Grid.php, src/Table.php, src/TableColumn/Generic.php
Fixes:
- Allow table filter to appear in Tabs fix #897 
- Better display of filtering icon fix #554 
Enhancement:
- Display column header name in a div using CSS class named "atk-table-column-header"
- Display sort icon on right side of column header
- Display column filtering icon under the column name
- allow to change filtering icon via CSS only
=> Fix/Table Popup - Dropdown

demos/grid.php
Fix:
- use new method name in Grid: Grid::addActionButton instead of Grid::addAction
=> fix/Demos grid.php

src/View.php
=> use one liner for jQuery selector

src/FormField/DropDown.php
=> Fix PHP notice - field can be null

src/FormField/AutoComplete.php, src/FormField/Lookup.php
Improve UX, more values are handled by GUI without any issues and they fit as well.
=> Change AutoComplete and Lookup default limit to 100 values

tests/DemoCallExitTest.php
- update page url for Table Filter popup test file.
=> Fix/Filter Popup test

README.md
=> Testing PR.

src/CRUD.php
=> [FIX] CRUD menu unnecessary destruction

demos/jsactions2.php, demos/jsactionsgrid.php, src/ActionExecutor/UserAction.php
Fix: #969 
- Move Preview to last step;
- Set model field's value to those use in Field step for preview.
=> fix/UserAction executor Field value in Preview

docs/quickstart.rst
Section "Requirements" specified twice, the second one being empty. Also id 25 later in the document should be 24.
Implementation of `<new feature>` (see ticket #..). Simple use:
``` php
$app->add(['new component']);
..
```
Typical use case of new feature explained here.
Drag a SCREENSHOT here:
- Documentation: [docs/file.rst](docs/file.rst)
- Demo: [demos/file.php](demos/file.php)
p.s. set label "in review" and assign reviewers if PR is complete. Otherwise set "work in progress" label.
=> Some cleanup

docs/form.rst, docs/render.rst, docs/view.rst, src/App.php, src/Form.php
Replacement of https://github.com/atk4/ui/pull/975
=> setLayout -> initLayout

demos/actions.php, demos/crud.php, demos/database.php, demos/grid_action.php, demos/init.php, demos/jsactions.php, demos/jssortable.php, demos/lister-ipp.php, demos/lister.php, demos/scroll-container.php, demos/scroll-lister.php, demos/table.php, demos/table2.php, demos/vue-component.php, docs/label.rst, docs/lister.rst, src/CRUD.php, src/CallbackLater.php, src/CardDeck.php, src/Form.php, src/FormField/CheckBox.php, src/FormField/MultiLine.php, src/FormField/Radio.php, src/FormLayout/Section/Accordion.php, src/TableColumn/FilterModel/Generic.php, src/TableColumn/Generic.php
related to https://github.com/atk4/ui/issues/966
=> [REFACTOR] rename addHook to onHook

demos/scroll-lister.php, src/TableColumn/Generic.php
Fixes #986
I will fix tomorrow, important as tests are failing as expected due https://github.com/atk4/core/pull/133
=> Fix hook trait usage

demos/jssortable.php, demos/lister-ipp.php, demos/lister.php, demos/scroll-container.php, demos/vue-component.php
=> Fix TravisCI/Behat tests

src/Menu.php
=> fix adding of sub-menus
